@route = compras

# @name postCompra
POST {{baseUrl}}/{{route}}
Content-Type: application/json

{
  "fornecedorId": 3,
  "data": "2025-09-06",
  "frete": 0,
  "outrasTaxas": 0,
  "itens": [
    {
      "produtoVariacaoId": 1,
      "quantidade": 5,
      "precoUnitario": 22.70
    },
    {
      "produtoVariacaoId": 2,
      "quantidade": 5,
      "precoUnitario": 7.78
    },
    {
      "produtoVariacaoId": 3,
      "quantidade": 5,
      "precoUnitario": 7.78
    },
    {
      "produtoVariacaoId": 4,
      "quantidade": 5,
      "precoUnitario": 2.70
    },
    {
      "produtoVariacaoId": 5,
      "quantidade": 5,
      "precoUnitario": 4.53
    },
    {
      "produtoVariacaoId": 6,
      "quantidade": 5,
      "precoUnitario": 9.27
    },
    {
      "produtoVariacaoId": 7,
      "quantidade": 5,
      "precoUnitario": 4.80
    }
  ],
  "formaPagamento": "CREDITO",
  "valorPago": 0,
  "quantidadeParcelas": 10
}
