@route = conjuntos

# @name postKit
POST {{baseUrl}}/{{route}}
Content-Type: application/json

{
  "nome": "Conjunto Top Kim com Bermuda Bolso",
  "descricao": null,
  "precoVenda": 169.90,
  "itens": [
    {
      "produtoId": 11,
      "quantidade": 1
    },
    {
      "produtoId": 12,
      "quantidade": 1
    }
  ]
}
