@route = kits

# @name postKit
POST {{baseUrl}}/{{route}}
Content-Type: application/json

{
  "nome": "Conjunto Top Lorena Plus com Legging Clássica",
  "descricao": null,
  "precoVenda": 179.90,
  "itens": [
    {
      "produtoId": 2,
      "quantidade": 1
    },
    {
      "produtoId": 3,
      "quantidade": 1
    }
  ]
}
