@route = produtos

# @name postProdutosComVariacoesLote
POST {{baseUrl}}/{{route}}/lote
Content-Type: application/json

[
  {
    "nome": "Gel Aromatizante Beijável Para Virilha Blow Girl 320ml Hot Flowers",
    "categoriaId": 2,
    "precoVenda": 59.90,
    "variacoes": [
      { "descricao": "Único" }
    ]
  },
  {
    "nome": "Gel Funcional Hot Ice e Vibra Xana Loka 15g Hot Flowers",
    "categoriaId": 2,
    "precoVenda": 24.90,
    "variacoes": [
      { "descricao": "Único" }
    ]
  },
  {
    "nome": "Gel Funcional Anal Kuloko 15g Hot Flowers",
    "categoriaId": 2,
    "precoVenda": 24.90,
    "variacoes": [
      { "descricao": "Único" }
    ]
  },
  {
    "nome": "Anel Peniano com Vibro Bichinho Mega Import",
    "categoriaId": 2,
    "precoVenda": 14.90,
    "variacoes": [
      { "descricao": "Único" }
    ]
  },
  {
    "nome": "Vibrador Bullet Ovo Vibratório Importação",
    "categoriaId": 2,
    "precoVenda": 19.90,
    "variacoes": [
      { "descricao": "Único" }
    ]
  },
  {
    "nome": "Vibrador Ponto G com Formato Golfinho Aveludado Importação",
    "categoriaId": 2,
    "precoVenda": 34.90,
    "variacoes": [
      { "descricao": "Único" }
    ]
  },
  {
    "nome": "Masturbador Egg Magical Kiss Mega Import",
    "categoriaId": 2,
    "precoVenda": 29.90,
    "variacoes": [
      { "descricao": "Único" }
    ]
  }
]
