@route = produtos

# @name postProdutosComVariacoesLote
POST {{baseUrl}}/{{route}}/lote
Content-Type: application/json

[
  {
    "nome": "Blusão Tule",
    "categoriaId": 1,
    "precoVenda": 69.90,
    "variacoes": [
      { "descricao": "Preto" },
      { "descricao": "Lavanda" },
      { "descricao": "Telha" },
      { "descricao": "Pink" }
    ]
  },
  {
    "nome": "Blusa Dry",
    "categoriaId": 1,
    "precoVenda": 69.90,
    "variacoes": [
      { "descricao": "Azul Índigo" },
      { "descricao": "Roxo" },
      { "descricao": "Rosa" },
      { "descricao": "Laranja" }
    ]
  },
  {
    "nome": "Regata Dry",
    "categoriaId": 1,
    "precoVenda": 69.90,
    "variacoes": [
      { "descricao": "Roxo Claro" }
    ]
  },
  {
    "nome": "Top Kim",
    "categoriaId": 1,
    "precoVenda": 59.90,
    "variacoes": [
      { "descricao": "Bicolor" }
    ]
  },
  {
    "nome": "Bermuda Bolso",
    "categoriaId": 1,
    "precoVenda": 110.00,
    "variacoes": [
      { "descricao": "Bicolor" }
    ]
  }
]
